server:
  port: 8085

spring:
  queries:
    users-query: select login, password, active from users where login=?
    roles-query: select login, role from users where u.login=?

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/userservice
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/liquibase/changelog-master.xml

hibernate:
  dialect: org.hibernate.dialect.H2Dialect