server:
  port: 8086

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:~/productservice

  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:/liquibase/changelog-master.xml

  servlet:
    multipart:
      enabled: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

hibernate:
  dialect: org.hibernate.dialect.H2Dialect

file:
  upload-dir: uploads

user-service-url: http://localhost:8085