server:
  port: 8086

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/productservice
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/liquibase/changelog-master.xml

hibernate:
  dialect: org.hibernate.dialect.H2Dialect